CREATE DATABASE RENTAL;
GO

USE RENTAL;
GO

CREATE TABLE EMPRESA(
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(40),
	endereco VARCHAR(190)
);
GO

CREATE TABLE VEICULO(
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	cor VARCHAR(15) NOT NULL,
	placa VARCHAR(8) NOT NULL
);
GO

CREATE TABLE CLIENTE(
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nome VARCHAR(15) NOT NULL,
	sobrenome VARCHAR(15),
	RG VARCHAR(12) NOT NULL
);
GO

CREATE TABLE ALUGUEL(
	idAluguel INT PRIMARY KEY IDENTITY(1,1),
	idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	preco SMALLMONEY NOT NULL,
	Adata DATE 
);
GO

drop table cliente
